/*
 * ============================================================================
 * FILE: chaincode/lib/certificate.js
 * ============================================================================
 * 
 * PURPOSE:
 *   Defines the Certificate class — the DATA MODEL for an academic certificate
 *   that gets stored on the Hyperledger Fabric blockchain. Every certificate
 *   issued through the platform becomes an instance of this class, serialized
 *   to JSON, and written to the blockchain's world state (the ledger).
 *
 * WHY THIS FILE EXISTS:
 *   Instead of storing raw JSON objects on the blockchain, we use a class to:
 *   1. Enforce a consistent structure — every certificate has the same fields
 *   2. Provide deserialization — convert raw JSON back into Certificate objects
 *   3. Self-document — the constructor clearly shows what data a certificate holds
 *
 * HOW IT CONNECTS TO OTHER FILES:
 *   - educert_contract.js → Creates Certificate instances when issuing/revoking
 *   - educert_contract.js → Deserializes Certificate objects when querying the ledger
 *   - The web-app NEVER imports this file directly — it only sees the JSON
 *     representation after querying the chaincode through Fabric SDK
 *
 * WHEN THIS FILE GETS EXECUTED:
 *   Inside Fabric peer containers whenever:
 *   - A university issues a new certificate (issueCertificate)
 *   - Someone queries a certificate (queryCertificateByUUID)
 *   - A certificate is revoked (revokeCertificate)
 *
 * DATA FLOW:
 *   Web App → Fabric SDK → Peer Node → loads this file → creates Certificate → 
 *   serializes to JSON → stores in CouchDB (world state)
 * ============================================================================
 */

// Enable strict mode for safer JavaScript execution
// (See index.js comments for detailed explanation of 'use strict')
'use strict';


// CONCEPT — class (Data Model / Domain Object):
//   This Certificate class is a "data model" — it represents a real-world thing
//   (an academic certificate) as a JavaScript object with specific properties.
//   In enterprise software, this pattern is called a "Domain Object" or "Entity".
//   The class gives structure to what would otherwise be an unstructured JSON blob.
class Certificate {
    /**
     * Constructor for the certificate transaction object. This will be written
     * to the blockchain ledger for each certificate issued.
     * 
     * STEP-BY-STEP WHAT HAPPENS WHEN CALLED:
     *   1. `new Certificate(hash, uniSig, stuSig, date, uuid, uniPK, stuPK)` is called
     *   2. JavaScript allocates memory for a new object
     *   3. The constructor runs, setting all properties on the new object
     *   4. The new object is returned and can be serialized to the blockchain
     *
     * @param {String} certHash            — SHA-256 hash created from the certificate data fields.
     *                                       This hash is what gets signed, not the raw data.
     * @param {String} universitySignature — Digital signature: the certHash encrypted with the
     *                                       university's PRIVATE key. Proves the university approved this cert.
     * @param {String} studentSignature    — Digital signature: the certHash encrypted with the
     *                                       student's PRIVATE key. Proves the student acknowledged this cert.
     * @param {String} dateOfIssuing       — ISO date string of when the certificate was issued
     * @param {String} certUUID            — Universally Unique Identifier for this specific certificate.
     *                                       Generated by the web-app. Used as the key in the blockchain.
     * @param {String} universityPK        — Public key (or public ID) of the issuing university's account
     * @param {String} studentPK           — Public key (or public ID) of the receiving student's account
     * @param {String} issuerEmail         — Email of the university that issued this certificate
     *                                       (Added later for ABAC — Attribute Based Access Control)
     */

    //todo: universityPK and studentPK should ideally be public keys. If you can't accomplish this, look into using 
    // some kind of UUID instead. 

    // CONCEPT — Default Parameters (issuerEmail = ""):
    //   ES6 allows you to set default values for function parameters.
    //   `issuerEmail = ""` means: if no issuerEmail is passed, use empty string.
    //   This provides backward compatibility — older code that doesn't pass
    //   issuerEmail will still work without breaking.
    // IF REMOVED: Calling `new Certificate(a,b,c,d,e,f,g)` without the 8th arg
    //   would set issuerEmail to `undefined` instead of "", which could cause
    //   issues when storing to the blockchain (undefined ≠ empty string in JSON).
    constructor(certHash, universitySignature, studentSignature, dateOfIssuing, certUUID, universityPK, studentPK, issuerEmail = "") {
        // Store the cryptographic hash of the certificate's content
        // WHAT: The SHA-256 hash computed from fields like universityName, major, cgpa, etc.
        // WHY: This hash is the "fingerprint" of the certificate. Any change to the data
        //   produces a completely different hash, making tampering detectable.
        // CRYPTO CONCEPT: Hash functions are one-way — you can go from data→hash but not hash→data.
        //   Two different inputs (almost) never produce the same hash.
        // IF REMOVED: No way to verify the certificate hasn't been tampered with.
        this.certHash = certHash;

        // Store the issuing university's public key
        // WHAT: Identifies WHICH university issued this certificate
        // WHY: During verification, the verifier uses this public key to check
        //   the university's signature. If the signature matches, it proves
        //   this specific university really did issue this certificate.
        // IF REMOVED: Verification would be impossible — you wouldn't know
        //   which public key to use to verify the signature.
        this.universityPK = universityPK;

        // Store the student's public key
        // WHAT: Identifies WHICH student received this certificate
        // WHY: Used to query "show me all certificates for this student"
        //   and to verify the student's signature on the certificate.
        // IF REMOVED: Can't look up certificates by student, can't verify
        //   student acknowledgment.
        this.studentPK = studentPK;

        // Store the university's digital signature
        // WHAT: The certHash signed (encrypted) with the university's PRIVATE key
        // WHY: This is the PROOF that the university approved this certificate.
        //   Anyone with the university's PUBLIC key can verify this signature.
        // CONCEPT — Digital Signatures:
        //   Private key + data → signature (only the key holder can create this)
        //   Public key + data + signature → true/false (anyone can verify this)
        //   It's like a wax seal that only the university can create but anyone can verify.
        // IF REMOVED: No proof the university actually issued this certificate.
        //   Anyone could forge certificates.
        this.universitySignature = universitySignature;

        // Store the student's digital signature
        // WHAT: The certHash signed with the student's PRIVATE key
        // WHY: Proves the student acknowledged and accepted this certificate.
        //   Prevents universities from issuing certificates without student consent.
        // IF REMOVED: No proof the student accepted this certificate.
        this.studentSignature = studentSignature;

        // Store the date of issuance
        // WHAT: When this certificate was issued (ISO date string, e.g., "2026-04-06")
        // WHY: Provides a timestamp for auditing and historical tracking
        // IF REMOVED: No record of when the certificate was created
        this.dateOfIssuing = dateOfIssuing;

        // Store the certificate's unique identifier
        // WHAT: A UUID (Universally Unique Identifier) like "550e8400-e29b-41d4-a716-446655440000"
        // WHY: This becomes the KEY in the blockchain's key-value store:
        //   "CERT" + certUUID → this certificate's JSON data
        //   UUIDs guarantee uniqueness across all certificates ever issued.
        // IF REMOVED: No way to uniquely identify or look up this specific certificate
        this.certUUID = certUUID;

        // Store the issuing university's email address
        // WHAT: Email like "krmu@krmu.edu.in" — identifies the issuing university
        // WHY: Used for ABAC (Attribute Based Access Control) — when revoking a certificate,
        //   the system checks: "Is the person trying to revoke this the same university
        //   that issued it?" This field enables that check.
        // IF REMOVED: Revocation ABAC breaks — any university could revoke another's certificates
        this.issuerEmail = issuerEmail;

        // Mark this object's type as "certificate"
        // WHAT: A discriminator field used for CouchDB queries
        // WHY: The blockchain stores multiple types of data (certificates, universities, schemas).
        //   When we query "get all certificates", we use: {selector: {dataType: "certificate"}}
        //   This field makes that query work.
        // IF REMOVED: CouchDB queries filtering by dataType would miss certificates
        this.dataType = "certificate";

        // Initialize revocation status to false (not revoked)
        // WHAT: Boolean flag — false = certificate is valid, true = certificate has been revoked
        // WHY: Certificates can be revoked (e.g., if fraud is discovered).
        //   Default is false because certificates are valid when first issued.
        // IF REMOVED: New certificates would have `revoked` as undefined,
        //   which could cause verification logic to behave incorrectly
        this.revoked = false;

        // Initialize the revocation reason to empty string
        // WHAT: Text explanation of why the certificate was revoked (empty if not revoked)
        // WHY: Provides transparency — when viewing a revoked cert, you can see why
        // IF REMOVED: No way to record WHY a certificate was revoked
        this.revokedReason = "";

        // Initialize the revocation timestamp to empty string
        // WHAT: ISO date string of when the certificate was revoked (empty if not revoked)
        // WHY: Creates an audit trail — important for legal and compliance purposes
        // IF REMOVED: No record of WHEN a revocation happened
        this.revokedAt = "";
    }



    /**
     * Instantiate a Certificate object from raw JSON data.
     * 
     * WHAT THIS METHOD DOES:
     *   Takes a plain JSON object (read from the blockchain) and converts it
     *   back into a proper Certificate class instance.
     *
     * WHY IT EXISTS (THE SERIALIZATION PROBLEM):
     *   When we store data on the blockchain, we do:
     *     JSON.stringify(certificateObject) → stores as a string
     *   When we read it back, we do:
     *     JSON.parse(stringFromBlockchain) → gives us a PLAIN object
     *   But this plain object is NOT a Certificate instance — it has no class
     *   methods. `deserialize()` fixes this by creating a new Certificate.
     *
     * CONCEPT — Serialization vs Deserialization:
     *   Serialization: Object → JSON string (for storage/transmission)
     *   Deserialization: JSON string → Object (for use in code)
     *   Think of it like packing a suitcase (serialize) vs unpacking (deserialize).
     *
     * CONCEPT — static method:
     *   Called on the CLASS itself: `Certificate.deserialize(data)`
     *   NOT on an instance: `myCert.deserialize(data)` ← WRONG
     *   Static methods are "factory methods" — they CREATE new instances.
     *
     * @param {json} data — Raw JSON data read from the blockchain
     * @returns {Certificate} — A proper Certificate instance with all properties
     */

    static deserialize(data) {
        // Create a new Certificate instance from the raw JSON fields
        // WHAT: Calls the constructor with values extracted from the JSON data
        // WHY: Converts raw data back into a structured object
        const cert = new Certificate(data.certHash, data.universitySignature, data.studentSignature, data.dateOfIssuing, data.certUUID, data.universityPK, data.studentPK, data.issuerEmail);

        // Restore the revocation status from stored data
        // WHAT: Sets revoked to the stored value, or false if it wasn't stored
        // WHY: Old certificates might not have these fields (backward compatibility)
        // CONCEPT — || (Logical OR as default):
        //   `data.revoked || false` means: use data.revoked if it exists and is truthy,
        //   otherwise use false. This is a common pattern for setting defaults.
        // IF REMOVED: Revoked certificates would lose their revocation status when queried
        cert.revoked = data.revoked || false;

        // Restore the revocation reason from stored data
        // WHAT: Sets the reason text, or empty string if not present
        cert.revokedReason = data.revokedReason || "";

        // Restore the revocation timestamp from stored data
        // WHAT: Sets the revocation date, or empty string if not present
        cert.revokedAt = data.revokedAt || "";

        // Return the fully reconstructed Certificate object
        // WHAT: Return the new Certificate instance to the caller
        // WHY: The caller needs a proper Certificate object, not raw JSON
        return cert;
    }


    //todo: Add validation of some kind to see that the signatures match and stuff. (LATER)
}

// Export the Certificate class so other files can use it
// WHAT: Makes Certificate available to educert_contract.js via require('./certificate')
// IF REMOVED: educert_contract.js would crash when trying to create Certificate objects
module.exports = Certificate;