/*
 * ============================================================================
 * FILE: web-app/services/fabric/wallet-utils.js
 * ============================================================================
 * 
 * PURPOSE:
 *   Helper functions for managing identities inside the Fabric Wallet.
 *   Takes the raw cryptographic material generated by the Fabric CA during
 *   enrollment and bundles it into an X.509 Identity object that the SDK
 *   can store in the encrypted wallet.
 * ============================================================================
 */

// const { Wallets } = require('fabric-network');
const config = require('../../loaders/config');
const fs = require('fs');
const path = require('path');
const logger = require('../logger');

/**
 * Adds a new user/entity to the wallet. Creates a separate json file to store hex keys of the user.
 * @param {FabricCAServices.IEnrollResponse} enrollmentObject
 * @param {String} userName
 * @returns {Promise<{} | Error>} public and private key in hex format;
 */

/*
 * ===== FUNCTION: createNewWalletEntity =====
 * WHAT: Packages the user's new certificates and imports them into the wallet.
 * WHY: When the CA issues a new identity, it comes back as raw byte strings.
 *   The Fabric SDK needs it formatted specifically as an X.509 identity object
 *   with credentials, an MSP ID, and type.
 * 
 * RETURNS: It also extracts the raw HEX values of the public and private keys
 *   and returns them so the registration process can safely store the public
 *   key on the blockchain and display the private key to the user once.
 */
async function createNewWalletEntity(enrollmentObject, userName) {
    // Access the MongoDB-backed wallet (works on both local and Vercel)
    const { getMongoWallet } = require('./mongo-wallet');
    const wallet = await getMongoWallet();

    // Parse the enrollment data into an X.509 Identity format
    // WHAT: X.509 is the standard format for public key certificates used on the web.
    // MSPID: Identifies which organization this user belongs to (Org1)
    const x509Identity = {
        credentials: {
            certificate: enrollmentObject.certificate,     // The public cert
            privateKey: enrollmentObject.key.toBytes(),    // The secret private key
        },
        mspId: 'Org1MSP',
        type: 'X.509',
    };

    // Extract the raw hex keys for the ECDSA signing algorithms
    // WHY: We need the hex public key to save on the blockchain for ABAC,
    //   and we need the hex private key to show the user upon registration.
    let hexKeyEntity = {
        publicKey: enrollmentObject.key._key.pubKeyHex || '',
        privateKey: enrollmentObject.key._key.prvKeyHex || '',
        userName: userName
    };

    // Store the formatted identity structure into MongoDB wallet
    await wallet.put(userName, x509Identity);

    // Return the hex representations back to the caller
    return hexKeyEntity;
}

/**
 * Note: loadHexKeysFromWallet was removed as it relied on insecure cleartext JSON storage.
 * Digital signatures and key management should be handled through the Fabric Network SDK.
 */

// Export the function for use in enrollment.js
module.exports = { createNewWalletEntity };